<select data-placeholder="Select a state..." class="opcion-icon-select-icons">
      <option data-icon="fa fa-glass" value="fa-glass">glass</option>
      <option data-icon="fa fa-music" value="fa-music">music</option>
      <option data-icon="fa fa-search" value="fa-search">search</option>
      <option data-icon="fa fa-envelope-o" value="fa-envelope-o">envelope-o</option>
      <option data-icon="fa fa-heart" value="fa-heart">heart</option>
      <option data-icon="fa fa-star" value="fa-star">star</option>
      <option data-icon="fa fa-star-o" value="fa-star-o">star-o</option>
      <option data-icon="fa fa-user" value="fa-user">user</option>
      <option data-icon="fa fa-film" value="fa-film">film</option>
      <option data-icon="fa fa-th-large" value="fa-th-large">th-large</option>
      <option data-icon="fa fa-th" value="fa-th">th</option>
      <option data-icon="fa fa-th-list" value="fa-th-list">th-list</option>
      <option data-icon="fa fa-check" value="fa-check">check</option>
      <option data-icon="fa fa-times" value="fa-times">times</option>
      <option data-icon="fa fa-search-plus" value="fa-search-plus">search-plus</option>
      <option data-icon="fa fa-search-minus" value="fa-search-minus">search-minus</option>
      <option data-icon="fa fa-power-off" value="fa-power-off">power-off</option>
      <option data-icon="fa fa-signal" value="fa-signal">signal</option>
      <option data-icon="fa fa-cog" value="fa-cog">cog</option>
      <option data-icon="fa fa-trash-o" value="fa-trash-o">trash-o</option>
      <option data-icon="fa fa-home" value="fa-home">home</option>
      <option data-icon="fa fa-file-o" value="fa-file-o">file-o</option>
      <option data-icon="fa fa-clock-o" value="fa-clock-o">clock-o</option>
      <option data-icon="fa fa-road" value="fa-road">road</option>
      <option data-icon="fa fa-download" value="fa-download">download</option>
      <option data-icon="fa fa-arrow-circle-o-down" value="fa-arrow-circle-o-down">arrow-circle-o-down</option>
      <option data-icon="fa fa-arrow-circle-o-up" value="fa-arrow-circle-o-up">arrow-circle-o-up</option>
      <option data-icon="fa fa-inbox" value="fa-inbox">inbox</option>
      <option data-icon="fa fa-play-circle-o" value="fa-play-circle-o">play-circle-o</option>
      <option data-icon="fa fa-repeat" value="fa-repeat">repeat</option>
      <option data-icon="fa fa-refresh" value="fa-refresh">refresh</option>
      <option data-icon="fa fa-list-alt" value="fa-list-alt">list-alt</option>
      <option data-icon="fa fa-lock" value="fa-lock">lock</option>
      <option data-icon="fa fa-flag" value="fa-flag">flag</option>
      <option data-icon="fa fa-headphones" value="fa-headphones">headphones</option>
      <option data-icon="fa fa-volume-off" value="fa-volume-off">volume-off</option>
      <option data-icon="fa fa-volume-down" value="fa-volume-down">volume-down</option>
      <option data-icon="fa fa-volume-up" value="fa-volume-up">volume-up</option>
      <option data-icon="fa fa-qrcode" value="fa-qrcode">qrcode</option>
      <option data-icon="fa fa-barcode" value="fa-barcode">barcode</option>
      <option data-icon="fa fa-tag" value="fa-tag">tag</option>
      <option data-icon="fa fa-tags" value="fa-tags">tags</option>
      <option data-icon="fa fa-book" value="fa-book">book</option>
      <option data-icon="fa fa-bookmark" value="fa-bookmark">bookmark</option>
      <option data-icon="fa fa-print" value="fa-print">print</option>
      <option data-icon="fa fa-camera" value="fa-camera">camera</option>
      <option data-icon="fa fa-font" value="fa-font">font</option>
      <option data-icon="fa fa-bold" value="fa-bold">bold</option>
      <option data-icon="fa fa-italic" value="fa-italic">italic</option>
      <option data-icon="fa fa-text-height" value="fa-text-height">text-height</option>
      <option data-icon="fa fa-text-width" value="fa-text-width">text-width</option>
      <option data-icon="fa fa-align-left" value="fa-align-left">align-left</option>
      <option data-icon="fa fa-align-center" value="fa-align-center">align-center</option>
      <option data-icon="fa fa-align-right" value="fa-align-right">align-right</option>
      <option data-icon="fa fa-align-justify" value="fa-align-justify">align-justify</option>
      <option data-icon="fa fa-list" value="fa-list">list</option>
      <option data-icon="fa fa-outdent" value="fa-outdent">outdent</option>
      <option data-icon="fa fa-indent" value="fa-indent">indent</option>
      <option data-icon="fa fa-video-camera" value="fa-video-camera">video-camera</option>
      <option data-icon="fa fa-picture-o" value="fa-picture-o">picture-o</option>
      <option data-icon="fa fa-pencil" value="fa-pencil">pencil</option>
      <option data-icon="fa fa-map-marker" value="fa-map-marker">map-marker</option>
      <option data-icon="fa fa-adjust" value="fa-adjust">adjust</option>
      <option data-icon="fa fa-tint" value="fa-tint">tint</option>
      <option data-icon="fa fa-pencil-square-o" value="fa-pencil-square-o">pencil-square-o</option>
      <option data-icon="fa fa-share-square-o" value="fa-share-square-o">share-square-o</option>
      <option data-icon="fa fa-check-square-o" value="fa-check-square-o">check-square-o</option>
      <option data-icon="fa fa-arrows" value="fa-arrows">arrows</option>
      <option data-icon="fa fa-step-backward" value="fa-step-backward">step-backward</option>
      <option data-icon="fa fa-fast-backward" value="fa-fast-backward">fast-backward</option>
      <option data-icon="fa fa-backward" value="fa-backward">backward</option>
      <option data-icon="fa fa-play" value="fa-play">play</option>
      <option data-icon="fa fa-pause" value="fa-pause">pause</option>
      <option data-icon="fa fa-stop" value="fa-stop">stop</option>
      <option data-icon="fa fa-forward" value="fa-forward">forward</option>
      <option data-icon="fa fa-fast-forward" value="fa-fast-forward">fast-forward</option>
      <option data-icon="fa fa-step-forward" value="fa-step-forward">step-forward</option>
      <option data-icon="fa fa-eject" value="fa-eject">eject</option>
      <option data-icon="fa fa-chevron-left" value="fa-chevron-left">chevron-left</option>
      <option data-icon="fa fa-chevron-right" value="fa-chevron-right">chevron-right</option>
      <option data-icon="fa fa-plus-circle" value="fa-plus-circle">plus-circle</option>
      <option data-icon="fa fa-minus-circle" value="fa-minus-circle">minus-circle</option>
      <option data-icon="fa fa-times-circle" value="fa-times-circle">times-circle</option>
      <option data-icon="fa fa-check-circle" value="fa-check-circle">check-circle</option>
      <option data-icon="fa fa-question-circle" value="fa-question-circle">question-circle</option>
      <option data-icon="fa fa-info-circle" value="fa-info-circle">info-circle</option>
      <option data-icon="fa fa-crosshairs" value="fa-crosshairs">crosshairs</option>
      <option data-icon="fa fa-times-circle-o" value="fa-times-circle-o">times-circle-o</option>
      <option data-icon="fa fa-check-circle-o" value="fa-check-circle-o">check-circle-o</option>
      <option data-icon="fa fa-ban" value="fa-ban">ban</option>
      <option data-icon="fa fa-arrow-left" value="fa-arrow-left">arrow-left</option>
      <option data-icon="fa fa-arrow-right" value="fa-arrow-right">arrow-right</option>
      <option data-icon="fa fa-arrow-up" value="fa-arrow-up">arrow-up</option>
      <option data-icon="fa fa-arrow-down" value="fa-arrow-down">arrow-down</option>
      <option data-icon="fa fa-share" value="fa-share">share</option>
      <option data-icon="fa fa-expand" value="fa-expand">expand</option>
      <option data-icon="fa fa-compress" value="fa-compress">compress</option>
      <option data-icon="fa fa-plus" value="fa-plus">plus</option>
      <option data-icon="fa fa-minus" value="fa-minus">minus</option>
      <option data-icon="fa fa-asterisk" value="fa-asterisk">asterisk</option>
      <option data-icon="fa fa-exclamation-circle" value="fa-exclamation-circle">exclamation-circle</option>
      <option data-icon="fa fa-gift" value="fa-gift">gift</option>
      <option data-icon="fa fa-leaf" value="fa-leaf">leaf</option>
      <option data-icon="fa fa-fire" value="fa-fire">fire</option>
      <option data-icon="fa fa-eye" value="fa-eye">eye</option>
      <option data-icon="fa fa-eye-slash" value="fa-eye-slash">eye-slash</option>
      <option data-icon="fa fa-exclamation-triangle" value="fa-exclamation-triangle">exclamation-triangle</option>
      <option data-icon="fa fa-plane" value="fa-plane">plane</option>
      <option data-icon="fa fa-calendar" value="fa-calendar">calendar</option>
      <option data-icon="fa fa-random" value="fa-random">random</option>
      <option data-icon="fa fa-comment" value="fa-comment">comment</option>
      <option data-icon="fa fa-magnet" value="fa-magnet">magnet</option>
      <option data-icon="fa fa-chevron-up" value="fa-chevron-up">chevron-up</option>
      <option data-icon="fa fa-chevron-down" value="fa-chevron-down">chevron-down</option>
      <option data-icon="fa fa-retweet" value="fa-retweet">retweet</option>
      <option data-icon="fa fa-shopping-cart" value="fa-shopping-cart">shopping-cart</option>
      <option data-icon="fa fa-folder" value="fa-folder">folder</option>
      <option data-icon="fa fa-folder-open" value="fa-folder-open">folder-open</option>
      <option data-icon="fa fa-arrows-v" value="fa-arrows-v">arrows-v</option>
      <option data-icon="fa fa-arrows-h" value="fa-arrows-h">arrows-h</option>
      <option data-icon="fa fa-bar-chart" value="fa-bar-chart">bar-chart</option>
      <option data-icon="fa fa-twitter-square" value="fa-twitter-square">twitter-square</option>
      <option data-icon="fa fa-facebook-square" value="fa-facebook-square">facebook-square</option>
      <option data-icon="fa fa-camera-retro" value="fa-camera-retro">camera-retro</option>
      <option data-icon="fa fa-key" value="fa-key">key</option>
      <option data-icon="fa fa-cogs" value="fa-cogs">cogs</option>
      <option data-icon="fa fa-comments" value="fa-comments">comments</option>
      <option data-icon="fa fa-thumbs-o-up" value="fa-thumbs-o-up">thumbs-o-up</option>
      <option data-icon="fa fa-thumbs-o-down" value="fa-thumbs-o-down">thumbs-o-down</option>
      <option data-icon="fa fa-star-half" value="fa-star-half">star-half</option>
      <option data-icon="fa fa-heart-o" value="fa-heart-o">heart-o</option>
      <option data-icon="fa fa-sign-out" value="fa-sign-out">sign-out</option>
      <option data-icon="fa fa-linkedin-square" value="fa-linkedin-square">linkedin-square</option>
      <option data-icon="fa fa-thumb-tack" value="fa-thumb-tack">thumb-tack</option>
      <option data-icon="fa fa-external-link" value="fa-external-link">external-link</option>
      <option data-icon="fa fa-sign-in" value="fa-sign-in">sign-in</option>
      <option data-icon="fa fa-trophy" value="fa-trophy">trophy</option>
      <option data-icon="fa fa-github-square" value="fa-github-square">github-square</option>
      <option data-icon="fa fa-upload" value="fa-upload">upload</option>
      <option data-icon="fa fa-lemon-o" value="fa-lemon-o">lemon-o</option>
      <option data-icon="fa fa-phone" value="fa-phone">phone</option>
      <option data-icon="fa fa-square-o" value="fa-square-o">square-o</option>
      <option data-icon="fa fa-bookmark-o" value="fa-bookmark-o">bookmark-o</option>
      <option data-icon="fa fa-phone-square" value="fa-phone-square">phone-square</option>
      <option data-icon="fa fa-twitter" value="fa-twitter">twitter</option>
      <option data-icon="fa fa-facebook" value="fa-facebook">facebook</option>
      <option data-icon="fa fa-github" value="fa-github">github</option>
      <option data-icon="fa fa-unlock" value="fa-unlock">unlock</option>
      <option data-icon="fa fa-credit-card" value="fa-credit-card">credit-card</option>
      <option data-icon="fa fa-rss" value="fa-rss">rss</option>
      <option data-icon="fa fa-hdd-o" value="fa-hdd-o">hdd-o</option>
      <option data-icon="fa fa-bullhorn" value="fa-bullhorn">bullhorn</option>
      <option data-icon="fa fa-bell" value="fa-bell">bell</option>
      <option data-icon="fa fa-certificate" value="fa-certificate">certificate</option>
      <option data-icon="fa fa-hand-o-right" value="fa-hand-o-right">hand-o-right</option>
      <option data-icon="fa fa-hand-o-left" value="fa-hand-o-left">hand-o-left</option>
      <option data-icon="fa fa-hand-o-up" value="fa-hand-o-up">hand-o-up</option>
      <option data-icon="fa fa-hand-o-down" value="fa-hand-o-down">hand-o-down</option>
      <option data-icon="fa fa-arrow-circle-left" value="fa-arrow-circle-left">arrow-circle-left</option>
      <option data-icon="fa fa-arrow-circle-right" value="fa-arrow-circle-right">arrow-circle-right</option>
      <option data-icon="fa fa-arrow-circle-up" value="fa-arrow-circle-up">arrow-circle-up</option>
      <option data-icon="fa fa-arrow-circle-down" value="fa-arrow-circle-down">arrow-circle-down</option>
      <option data-icon="fa fa-globe" value="fa-globe">globe</option>
      <option data-icon="fa fa-wrench" value="fa-wrench">wrench</option>
      <option data-icon="fa fa-tasks" value="fa-tasks">tasks</option>
      <option data-icon="fa fa-filter" value="fa-filter">filter</option>
      <option data-icon="fa fa-briefcase" value="fa-briefcase">briefcase</option>
      <option data-icon="fa fa-arrows-alt" value="fa-arrows-alt">arrows-alt</option>
      <option data-icon="fa fa-users" value="fa-users">users</option>
      <option data-icon="fa fa-link" value="fa-link">link</option>
      <option data-icon="fa fa-cloud" value="fa-cloud">cloud</option>
      <option data-icon="fa fa-flask" value="fa-flask">flask</option>
      <option data-icon="fa fa-scissors" value="fa-scissors">scissors</option>
      <option data-icon="fa fa-files-o" value="fa-files-o">files-o</option>
      <option data-icon="fa fa-paperclip" value="fa-paperclip">paperclip</option>
      <option data-icon="fa fa-floppy-o" value="fa-floppy-o">floppy-o</option>
      <option data-icon="fa fa-square" value="fa-square">square</option>
      <option data-icon="fa fa-bars" value="fa-bars">bars</option>
      <option data-icon="fa fa-list-ul" value="fa-list-ul">list-ul</option>
      <option data-icon="fa fa-list-ol" value="fa-list-ol">list-ol</option>
      <option data-icon="fa fa-strikethrough" value="fa-strikethrough">strikethrough</option>
      <option data-icon="fa fa-underline" value="fa-underline">underline</option>
      <option data-icon="fa fa-table" value="fa-table">table</option>
      <option data-icon="fa fa-magic" value="fa-magic">magic</option>
      <option data-icon="fa fa-truck" value="fa-truck">truck</option>
      <option data-icon="fa fa-pinterest" value="fa-pinterest">pinterest</option>
      <option data-icon="fa fa-pinterest-square" value="fa-pinterest-square">pinterest-square</option>
      <option data-icon="fa fa-google-plus-square" value="fa-google-plus-square">google-plus-square</option>
      <option data-icon="fa fa-google-plus" value="fa-google-plus">google-plus</option>
      <option data-icon="fa fa-money" value="fa-money">money</option>
      <option data-icon="fa fa-caret-down" value="fa-caret-down">caret-down</option>
      <option data-icon="fa fa-caret-up" value="fa-caret-up">caret-up</option>
      <option data-icon="fa fa-caret-left" value="fa-caret-left">caret-left</option>
      <option data-icon="fa fa-caret-right" value="fa-caret-right">caret-right</option>
      <option data-icon="fa fa-columns" value="fa-columns">columns</option>
      <option data-icon="fa fa-sort" value="fa-sort">sort</option>
      <option data-icon="fa fa-sort-desc" value="fa-sort-desc">sort-desc</option>
      <option data-icon="fa fa-sort-asc" value="fa-sort-asc">sort-asc</option>
      <option data-icon="fa fa-envelope" value="fa-envelope">envelope</option>
      <option data-icon="fa fa-linkedin" value="fa-linkedin">linkedin</option>
      <option data-icon="fa fa-undo" value="fa-undo">undo</option>
      <option data-icon="fa fa-gavel" value="fa-gavel">gavel</option>
      <option data-icon="fa fa-tachometer" value="fa-tachometer">tachometer</option>
      <option data-icon="fa fa-comment-o" value="fa-comment-o">comment-o</option>
      <option data-icon="fa fa-comments-o" value="fa-comments-o">comments-o</option>
      <option data-icon="fa fa-bolt" value="fa-bolt">bolt</option>
      <option data-icon="fa fa-sitemap" value="fa-sitemap">sitemap</option>
      <option data-icon="fa fa-umbrella" value="fa-umbrella">umbrella</option>
      <option data-icon="fa fa-clipboard" value="fa-clipboard">clipboard</option>
      <option data-icon="fa fa-lightbulb-o" value="fa-lightbulb-o">lightbulb-o</option>
      <option data-icon="fa fa-exchange" value="fa-exchange">exchange</option>
      <option data-icon="fa fa-cloud-download" value="fa-cloud-download">cloud-download</option>
      <option data-icon="fa fa-cloud-upload" value="fa-cloud-upload">cloud-upload</option>
      <option data-icon="fa fa-user-md" value="fa-user-md">user-md</option>
      <option data-icon="fa fa-stethoscope" value="fa-stethoscope">stethoscope</option>
      <option data-icon="fa fa-suitcase" value="fa-suitcase">suitcase</option>
      <option data-icon="fa fa-bell-o" value="fa-bell-o">bell-o</option>
      <option data-icon="fa fa-coffee" value="fa-coffee">coffee</option>
      <option data-icon="fa fa-cutlery" value="fa-cutlery">cutlery</option>
      <option data-icon="fa fa-file-text-o" value="fa-file-text-o">file-text-o</option>
      <option data-icon="fa fa-building-o" value="fa-building-o">building-o</option>
      <option data-icon="fa fa-hospital-o" value="fa-hospital-o">hospital-o</option>
      <option data-icon="fa fa-ambulance" value="fa-ambulance">ambulance</option>
      <option data-icon="fa fa-medkit" value="fa-medkit">medkit</option>
      <option data-icon="fa fa-fighter-jet" value="fa-fighter-jet">fighter-jet</option>
      <option data-icon="fa fa-beer" value="fa-beer">beer</option>
      <option data-icon="fa fa-h-square" value="fa-h-square">h-square</option>
      <option data-icon="fa fa-plus-square" value="fa-plus-square">plus-square</option>
      <option data-icon="fa fa-angle-double-left" value="fa-angle-double-left">angle-double-left</option>
      <option data-icon="fa fa-angle-double-right" value="fa-angle-double-right">angle-double-right</option>
      <option data-icon="fa fa-angle-double-up" value="fa-angle-double-up">angle-double-up</option>
      <option data-icon="fa fa-angle-double-down" value="fa-angle-double-down">angle-double-down</option>
      <option data-icon="fa fa-angle-left" value="fa-angle-left">angle-left</option>
      <option data-icon="fa fa-angle-right" value="fa-angle-right">angle-right</option>
      <option data-icon="fa fa-angle-up" value="fa-angle-up">angle-up</option>
      <option data-icon="fa fa-angle-down" value="fa-angle-down">angle-down</option>
      <option data-icon="fa fa-desktop" value="fa-desktop">desktop</option>
      <option data-icon="fa fa-laptop" value="fa-laptop">laptop</option>
      <option data-icon="fa fa-tablet" value="fa-tablet">tablet</option>
      <option data-icon="fa fa-mobile" value="fa-mobile">mobile</option>
      <option data-icon="fa fa-circle-o" value="fa-circle-o">circle-o</option>
      <option data-icon="fa fa-quote-left" value="fa-quote-left">quote-left</option>
      <option data-icon="fa fa-quote-right" value="fa-quote-right">quote-right</option>
      <option data-icon="fa fa-spinner" value="fa-spinner">spinner</option>
      <option data-icon="fa fa-circle" value="fa-circle">circle</option>
      <option data-icon="fa fa-reply" value="fa-reply">reply</option>
      <option data-icon="fa fa-github-alt" value="fa-github-alt">github-alt</option>
      <option data-icon="fa fa-folder-o" value="fa-folder-o">folder-o</option>
      <option data-icon="fa fa-folder-open-o" value="fa-folder-open-o">folder-open-o</option>
      <option data-icon="fa fa-smile-o" value="fa-smile-o">smile-o</option>
      <option data-icon="fa fa-frown-o" value="fa-frown-o">frown-o</option>
      <option data-icon="fa fa-meh-o" value="fa-meh-o">meh-o</option>
      <option data-icon="fa fa-gamepad" value="fa-gamepad">gamepad</option>
      <option data-icon="fa fa-keyboard-o" value="fa-keyboard-o">keyboard-o</option>
      <option data-icon="fa fa-flag-o" value="fa-flag-o">flag-o</option>
      <option data-icon="fa fa-flag-checkered" value="fa-flag-checkered">flag-checkered</option>
      <option data-icon="fa fa-terminal" value="fa-terminal">terminal</option>
      <option data-icon="fa fa-code" value="fa-code">code</option>
      <option data-icon="fa fa-reply-all" value="fa-reply-all">reply-all</option>
      <option data-icon="fa fa-star-half-o" value="fa-star-half-o">star-half-o</option>
      <option data-icon="fa fa-location-arrow" value="fa-location-arrow">location-arrow</option>
      <option data-icon="fa fa-crop" value="fa-crop">crop</option>
      <option data-icon="fa fa-code-fork" value="fa-code-fork">code-fork</option>
      <option data-icon="fa fa-chain-broken" value="fa-chain-broken">chain-broken</option>
      <option data-icon="fa fa-question" value="fa-question">question</option>
      <option data-icon="fa fa-info" value="fa-info">info</option>
      <option data-icon="fa fa-exclamation" value="fa-exclamation">exclamation</option>
      <option data-icon="fa fa-superscript" value="fa-superscript">superscript</option>
      <option data-icon="fa fa-subscript" value="fa-subscript">subscript</option>
      <option data-icon="fa fa-eraser" value="fa-eraser">eraser</option>
      <option data-icon="fa fa-puzzle-piece" value="fa-puzzle-piece">puzzle-piece</option>
      <option data-icon="fa fa-microphone" value="fa-microphone">microphone</option>
      <option data-icon="fa fa-microphone-slash" value="fa-microphone-slash">microphone-slash</option>
      <option data-icon="fa fa-shield" value="fa-shield">shield</option>
      <option data-icon="fa fa-calendar-o" value="fa-calendar-o">calendar-o</option>
      <option data-icon="fa fa-fire-extinguisher" value="fa-fire-extinguisher">fire-extinguisher</option>
      <option data-icon="fa fa-rocket" value="fa-rocket">rocket</option>
      <option data-icon="fa fa-maxcdn" value="fa-maxcdn">maxcdn</option>
      <option data-icon="fa fa-chevron-circle-left" value="fa-chevron-circle-left">chevron-circle-left</option>
      <option data-icon="fa fa-chevron-circle-right" value="fa-chevron-circle-right">chevron-circle-right</option>
      <option data-icon="fa fa-chevron-circle-up" value="fa-chevron-circle-up">chevron-circle-up</option>
      <option data-icon="fa fa-chevron-circle-down" value="fa-chevron-circle-down">chevron-circle-down</option>
      <option data-icon="fa fa-html5" value="fa-html5">html5</option>
      <option data-icon="fa fa-css3" value="fa-css3">css3</option>
      <option data-icon="fa fa-anchor" value="fa-anchor">anchor</option>
      <option data-icon="fa fa-unlock-alt" value="fa-unlock-alt">unlock-alt</option>
      <option data-icon="fa fa-bullseye" value="fa-bullseye">bullseye</option>
      <option data-icon="fa fa-ellipsis-h" value="fa-ellipsis-h">ellipsis-h</option>
      <option data-icon="fa fa-ellipsis-v" value="fa-ellipsis-v">ellipsis-v</option>
      <option data-icon="fa fa-rss-square" value="fa-rss-square">rss-square</option>
      <option data-icon="fa fa-play-circle" value="fa-play-circle">play-circle</option>
      <option data-icon="fa fa-ticket" value="fa-ticket">ticket</option>
      <option data-icon="fa fa-minus-square" value="fa-minus-square">minus-square</option>
      <option data-icon="fa fa-minus-square-o" value="fa-minus-square-o">minus-square-o</option>
      <option data-icon="fa fa-level-up" value="fa-level-up">level-up</option>
      <option data-icon="fa fa-level-down" value="fa-level-down">level-down</option>
      <option data-icon="fa fa-check-square" value="fa-check-square">check-square</option>
      <option data-icon="fa fa-pencil-square" value="fa-pencil-square">pencil-square</option>
      <option data-icon="fa fa-external-link-square" value="fa-external-link-square">external-link-square</option>
      <option data-icon="fa fa-share-square" value="fa-share-square">share-square</option>
      <option data-icon="fa fa-compass" value="fa-compass">compass</option>
      <option data-icon="fa fa-caret-square-o-down" value="fa-caret-square-o-down">caret-square-o-down</option>
      <option data-icon="fa fa-caret-square-o-up" value="fa-caret-square-o-up">caret-square-o-up</option>
      <option data-icon="fa fa-caret-square-o-right" value="fa-caret-square-o-right">caret-square-o-right</option>
      <option data-icon="fa fa-eur" value="fa-eur">eur</option>
      <option data-icon="fa fa-gbp" value="fa-gbp">gbp</option>
      <option data-icon="fa fa-usd" value="fa-usd">usd</option>
      <option data-icon="fa fa-inr" value="fa-inr">inr</option>
      <option data-icon="fa fa-jpy" value="fa-jpy">jpy</option>
      <option data-icon="fa fa-rub" value="fa-rub">rub</option>
      <option data-icon="fa fa-krw" value="fa-krw">krw</option>
      <option data-icon="fa fa-btc" value="fa-btc">btc</option>
      <option data-icon="fa fa-file" value="fa-file">file</option>
      <option data-icon="fa fa-file-text" value="fa-file-text">file-text</option>
      <option data-icon="fa fa-sort-alpha-asc" value="fa-sort-alpha-asc">sort-alpha-asc</option>
      <option data-icon="fa fa-sort-alpha-desc" value="fa-sort-alpha-desc">sort-alpha-desc</option>
      <option data-icon="fa fa-sort-amount-asc" value="fa-sort-amount-asc">sort-amount-asc</option>
      <option data-icon="fa fa-sort-amount-desc" value="fa-sort-amount-desc">sort-amount-desc</option>
      <option data-icon="fa fa-sort-numeric-asc" value="fa-sort-numeric-asc">sort-numeric-asc</option>
      <option data-icon="fa fa-sort-numeric-desc" value="fa-sort-numeric-desc">sort-numeric-desc</option>
      <option data-icon="fa fa-thumbs-up" value="fa-thumbs-up">thumbs-up</option>
      <option data-icon="fa fa-thumbs-down" value="fa-thumbs-down">thumbs-down</option>
      <option data-icon="fa fa-youtube-square" value="fa-youtube-square">youtube-square</option>
      <option data-icon="fa fa-youtube" value="fa-youtube">youtube</option>
      <option data-icon="fa fa-xing" value="fa-xing">xing</option>
      <option data-icon="fa fa-xing-square" value="fa-xing-square">xing-square</option>
      <option data-icon="fa fa-youtube-play" value="fa-youtube-play">youtube-play</option>
      <option data-icon="fa fa-dropbox" value="fa-dropbox">dropbox</option>
      <option data-icon="fa fa-stack-overflow" value="fa-stack-overflow">stack-overflow</option>
      <option data-icon="fa fa-instagram" value="fa-instagram">instagram</option>
      <option data-icon="fa fa-flickr" value="fa-flickr">flickr</option>
      <option data-icon="fa fa-adn" value="fa-adn">adn</option>
      <option data-icon="fa fa-bitbucket" value="fa-bitbucket">bitbucket</option>
      <option data-icon="fa fa-bitbucket-square" value="fa-bitbucket-square">bitbucket-square</option>
      <option data-icon="fa fa-tumblr" value="fa-tumblr">tumblr</option>
      <option data-icon="fa fa-tumblr-square" value="fa-tumblr-square">tumblr-square</option>
      <option data-icon="fa fa-long-arrow-down" value="fa-long-arrow-down">long-arrow-down</option>
      <option data-icon="fa fa-long-arrow-up" value="fa-long-arrow-up">long-arrow-up</option>
      <option data-icon="fa fa-long-arrow-left" value="fa-long-arrow-left">long-arrow-left</option>
      <option data-icon="fa fa-long-arrow-right" value="fa-long-arrow-right">long-arrow-right</option>
      <option data-icon="fa fa-apple" value="fa-apple">apple</option>
      <option data-icon="fa fa-windows" value="fa-windows">windows</option>
      <option data-icon="fa fa-android" value="fa-android">android</option>
      <option data-icon="fa fa-linux" value="fa-linux">linux</option>
      <option data-icon="fa fa-dribbble" value="fa-dribbble">dribbble</option>
      <option data-icon="fa fa-skype" value="fa-skype">skype</option>
      <option data-icon="fa fa-foursquare" value="fa-foursquare">foursquare</option>
      <option data-icon="fa fa-trello" value="fa-trello">trello</option>
      <option data-icon="fa fa-female" value="fa-female">female</option>
      <option data-icon="fa fa-male" value="fa-male">male</option>
      <option data-icon="fa fa-gratipay" value="fa-gratipay">gratipay</option>
      <option data-icon="fa fa-sun-o" value="fa-sun-o">sun-o</option>
      <option data-icon="fa fa-moon-o" value="fa-moon-o">moon-o</option>
      <option data-icon="fa fa-archive" value="fa-archive">archive</option>
      <option data-icon="fa fa-bug" value="fa-bug">bug</option>
      <option data-icon="fa fa-vk" value="fa-vk">vk</option>
      <option data-icon="fa fa-weibo" value="fa-weibo">weibo</option>
      <option data-icon="fa fa-renren" value="fa-renren">renren</option>
      <option data-icon="fa fa-pagelines" value="fa-pagelines">pagelines</option>
      <option data-icon="fa fa-stack-exchange" value="fa-stack-exchange">stack-exchange</option>
      <option data-icon="fa fa-arrow-circle-o-right" value="fa-arrow-circle-o-right">arrow-circle-o-right</option>
      <option data-icon="fa fa-arrow-circle-o-left" value="fa-arrow-circle-o-left">arrow-circle-o-left</option>
      <option data-icon="fa fa-caret-square-o-left" value="fa-caret-square-o-left">caret-square-o-left</option>
      <option data-icon="fa fa-dot-circle-o" value="fa-dot-circle-o">dot-circle-o</option>
      <option data-icon="fa fa-wheelchair" value="fa-wheelchair">wheelchair</option>
      <option data-icon="fa fa-vimeo-square" value="fa-vimeo-square">vimeo-square</option>
      <option data-icon="fa fa-try" value="fa-try">try</option>
      <option data-icon="fa fa-plus-square-o" value="fa-plus-square-o">plus-square-o</option>
      <option data-icon="fa fa-space-shuttle" value="fa-space-shuttle">space-shuttle</option>
      <option data-icon="fa fa-slack" value="fa-slack">slack</option>
      <option data-icon="fa fa-envelope-square" value="fa-envelope-square">envelope-square</option>
      <option data-icon="fa fa-wordpress" value="fa-wordpress">wordpress</option>
      <option data-icon="fa fa-openid" value="fa-openid">openid</option>
      <option data-icon="fa fa-university" value="fa-university">university</option>
      <option data-icon="fa fa-graduation-cap" value="fa-graduation-cap">graduation-cap</option>
      <option data-icon="fa fa-yahoo" value="fa-yahoo">yahoo</option>
      <option data-icon="fa fa-google" value="fa-google">google</option>
      <option data-icon="fa fa-reddit" value="fa-reddit">reddit</option>
      <option data-icon="fa fa-reddit-square" value="fa-reddit-square">reddit-square</option>
      <option data-icon="fa fa-stumbleupon-circle" value="fa-stumbleupon-circle">stumbleupon-circle</option>
      <option data-icon="fa fa-stumbleupon" value="fa-stumbleupon">stumbleupon</option>
      <option data-icon="fa fa-delicious" value="fa-delicious">delicious</option>
      <option data-icon="fa fa-digg" value="fa-digg">digg</option>
      <option data-icon="fa fa-pied-piper" value="fa-pied-piper">pied-piper</option>
      <option data-icon="fa fa-pied-piper-alt" value="fa-pied-piper-alt">pied-piper-alt</option>
      <option data-icon="fa fa-drupal" value="fa-drupal">drupal</option>
      <option data-icon="fa fa-joomla" value="fa-joomla">joomla</option>
      <option data-icon="fa fa-language" value="fa-language">language</option>
      <option data-icon="fa fa-fax" value="fa-fax">fax</option>
      <option data-icon="fa fa-building" value="fa-building">building</option>
      <option data-icon="fa fa-child" value="fa-child">child</option>
      <option data-icon="fa fa-paw" value="fa-paw">paw</option>
      <option data-icon="fa fa-spoon" value="fa-spoon">spoon</option>
      <option data-icon="fa fa-cube" value="fa-cube">cube</option>
      <option data-icon="fa fa-cubes" value="fa-cubes">cubes</option>
      <option data-icon="fa fa-behance" value="fa-behance">behance</option>
      <option data-icon="fa fa-behance-square" value="fa-behance-square">behance-square</option>
      <option data-icon="fa fa-steam" value="fa-steam">steam</option>
      <option data-icon="fa fa-steam-square" value="fa-steam-square">steam-square</option>
      <option data-icon="fa fa-recycle" value="fa-recycle">recycle</option>
      <option data-icon="fa fa-car" value="fa-car">car</option>
      <option data-icon="fa fa-taxi" value="fa-taxi">taxi</option>
      <option data-icon="fa fa-tree" value="fa-tree">tree</option>
      <option data-icon="fa fa-spotify" value="fa-spotify">spotify</option>
      <option data-icon="fa fa-deviantart" value="fa-deviantart">deviantart</option>
      <option data-icon="fa fa-soundcloud" value="fa-soundcloud">soundcloud</option>
      <option data-icon="fa fa-database" value="fa-database">database</option>
      <option data-icon="fa fa-file-pdf-o" value="fa-file-pdf-o">file-pdf-o</option>
      <option data-icon="fa fa-file-word-o" value="fa-file-word-o">file-word-o</option>
      <option data-icon="fa fa-file-excel-o" value="fa-file-excel-o">file-excel-o</option>
      <option data-icon="fa fa-file-powerpoint-o" value="fa-file-powerpoint-o">file-powerpoint-o</option>
      <option data-icon="fa fa-file-image-o" value="fa-file-image-o">file-image-o</option>
      <option data-icon="fa fa-file-archive-o" value="fa-file-archive-o">file-archive-o</option>
      <option data-icon="fa fa-file-audio-o" value="fa-file-audio-o">file-audio-o</option>
      <option data-icon="fa fa-file-video-o" value="fa-file-video-o">file-video-o</option>
      <option data-icon="fa fa-file-code-o" value="fa-file-code-o">file-code-o</option>
      <option data-icon="fa fa-vine" value="fa-vine">vine</option>
      <option data-icon="fa fa-codepen" value="fa-codepen">codepen</option>
      <option data-icon="fa fa-jsfiddle" value="fa-jsfiddle">jsfiddle</option>
      <option data-icon="fa fa-life-ring" value="fa-life-ring">life-ring</option>
      <option data-icon="fa fa-circle-o-notch" value="fa-circle-o-notch">circle-o-notch</option>
      <option data-icon="fa fa-rebel" value="fa-rebel">rebel</option>
      <option data-icon="fa fa-empire" value="fa-empire">empire</option>
      <option data-icon="fa fa-git-square" value="fa-git-square">git-square</option>
      <option data-icon="fa fa-git" value="fa-git">git</option>
      <option data-icon="fa fa-hacker-news" value="fa-hacker-news">hacker-news</option>
      <option data-icon="fa fa-tencent-weibo" value="fa-tencent-weibo">tencent-weibo</option>
      <option data-icon="fa fa-qq" value="fa-qq">qq</option>
      <option data-icon="fa fa-weixin" value="fa-weixin">weixin</option>
      <option data-icon="fa fa-paper-plane" value="fa-paper-plane">paper-plane</option>
      <option data-icon="fa fa-paper-plane-o" value="fa-paper-plane-o">paper-plane-o</option>
      <option data-icon="fa fa-history" value="fa-history">history</option>
      <option data-icon="fa fa-circle-thin" value="fa-circle-thin">circle-thin</option>
      <option data-icon="fa fa-header" value="fa-header">header</option>
      <option data-icon="fa fa-paragraph" value="fa-paragraph">paragraph</option>
      <option data-icon="fa fa-sliders" value="fa-sliders">sliders</option>
      <option data-icon="fa fa-share-alt" value="fa-share-alt">share-alt</option>
      <option data-icon="fa fa-share-alt-square" value="fa-share-alt-square">share-alt-square</option>
      <option data-icon="fa fa-bomb" value="fa-bomb">bomb</option>
      <option data-icon="fa fa-futbol-o" value="fa-futbol-o">futbol-o</option>
      <option data-icon="fa fa-tty" value="fa-tty">tty</option>
      <option data-icon="fa fa-binoculars" value="fa-binoculars">binoculars</option>
      <option data-icon="fa fa-plug" value="fa-plug">plug</option>
      <option data-icon="fa fa-slideshare" value="fa-slideshare">slideshare</option>
      <option data-icon="fa fa-twitch" value="fa-twitch">twitch</option>
      <option data-icon="fa fa-yelp" value="fa-yelp">yelp</option>
      <option data-icon="fa fa-newspaper-o" value="fa-newspaper-o">newspaper-o</option>
      <option data-icon="fa fa-wifi" value="fa-wifi">wifi</option>
      <option data-icon="fa fa-calculator" value="fa-calculator">calculator</option>
      <option data-icon="fa fa-paypal" value="fa-paypal">paypal</option>
      <option data-icon="fa fa-google-wallet" value="fa-google-wallet">google-wallet</option>
      <option data-icon="fa fa-cc-visa" value="fa-cc-visa">cc-visa</option>
      <option data-icon="fa fa-cc-mastercard" value="fa-cc-mastercard">cc-mastercard</option>
      <option data-icon="fa fa-cc-discover" value="fa-cc-discover">cc-discover</option>
      <option data-icon="fa fa-cc-amex" value="fa-cc-amex">cc-amex</option>
      <option data-icon="fa fa-cc-paypal" value="fa-cc-paypal">cc-paypal</option>
      <option data-icon="fa fa-cc-stripe" value="fa-cc-stripe">cc-stripe</option>
      <option data-icon="fa fa-bell-slash" value="fa-bell-slash">bell-slash</option>
      <option data-icon="fa fa-bell-slash-o" value="fa-bell-slash-o">bell-slash-o</option>
      <option data-icon="fa fa-trash" value="fa-trash">trash</option>
      <option data-icon="fa fa-copyright" value="fa-copyright">copyright</option>
      <option data-icon="fa fa-at" value="fa-at">at</option>
      <option data-icon="fa fa-eyedropper" value="fa-eyedropper">eyedropper</option>
      <option data-icon="fa fa-paint-brush" value="fa-paint-brush">paint-brush</option>
      <option data-icon="fa fa-birthday-cake" value="fa-birthday-cake">birthday-cake</option>
      <option data-icon="fa fa-area-chart" value="fa-area-chart">area-chart</option>
      <option data-icon="fa fa-pie-chart" value="fa-pie-chart">pie-chart</option>
      <option data-icon="fa fa-line-chart" value="fa-line-chart">line-chart</option>
      <option data-icon="fa fa-lastfm" value="fa-lastfm">lastfm</option>
      <option data-icon="fa fa-lastfm-square" value="fa-lastfm-square">lastfm-square</option>
      <option data-icon="fa fa-toggle-off" value="fa-toggle-off">toggle-off</option>
      <option data-icon="fa fa-toggle-on" value="fa-toggle-on">toggle-on</option>
      <option data-icon="fa fa-bicycle" value="fa-bicycle">bicycle</option>
      <option data-icon="fa fa-bus" value="fa-bus">bus</option>
      <option data-icon="fa fa-ioxhost" value="fa-ioxhost">ioxhost</option>
      <option data-icon="fa fa-angellist" value="fa-angellist">angellist</option>
      <option data-icon="fa fa-cc" value="fa-cc">cc</option>
      <option data-icon="fa fa-ils" value="fa-ils">ils</option>
      <option data-icon="fa fa-meanpath" value="fa-meanpath">meanpath</option>
      <option data-icon="fa fa-buysellads" value="fa-buysellads">buysellads</option>
      <option data-icon="fa fa-connectdevelop" value="fa-connectdevelop">connectdevelop</option>
      <option data-icon="fa fa-dashcube" value="fa-dashcube">dashcube</option>
      <option data-icon="fa fa-forumbee" value="fa-forumbee">forumbee</option>
      <option data-icon="fa fa-leanpub" value="fa-leanpub">leanpub</option>
      <option data-icon="fa fa-sellsy" value="fa-sellsy">sellsy</option>
      <option data-icon="fa fa-shirtsinbulk" value="fa-shirtsinbulk">shirtsinbulk</option>
      <option data-icon="fa fa-simplybuilt" value="fa-simplybuilt">simplybuilt</option>
      <option data-icon="fa fa-skyatlas" value="fa-skyatlas">skyatlas</option>
      <option data-icon="fa fa-cart-plus" value="fa-cart-plus">cart-plus</option>
      <option data-icon="fa fa-cart-arrow-down" value="fa-cart-arrow-down">cart-arrow-down</option>
      <option data-icon="fa fa-diamond" value="fa-diamond">diamond</option>
      <option data-icon="fa fa-ship" value="fa-ship">ship</option>
      <option data-icon="fa fa-user-secret" value="fa-user-secret">user-secret</option>
      <option data-icon="fa fa-motorcycle" value="fa-motorcycle">motorcycle</option>
      <option data-icon="fa fa-street-view" value="fa-street-view">street-view</option>
      <option data-icon="fa fa-heartbeat" value="fa-heartbeat">heartbeat</option>
      <option data-icon="fa fa-venus" value="fa-venus">venus</option>
      <option data-icon="fa fa-mars" value="fa-mars">mars</option>
      <option data-icon="fa fa-mercury" value="fa-mercury">mercury</option>
      <option data-icon="fa fa-transgender" value="fa-transgender">transgender</option>
      <option data-icon="fa fa-transgender-alt" value="fa-transgender-alt">transgender-alt</option>
      <option data-icon="fa fa-venus-double" value="fa-venus-double">venus-double</option>
      <option data-icon="fa fa-mars-double" value="fa-mars-double">mars-double</option>
      <option data-icon="fa fa-venus-mars" value="fa-venus-mars">venus-mars</option>
      <option data-icon="fa fa-mars-stroke" value="fa-mars-stroke">mars-stroke</option>
      <option data-icon="fa fa-mars-stroke-v" value="fa-mars-stroke-v">mars-stroke-v</option>
      <option data-icon="fa fa-mars-stroke-h" value="fa-mars-stroke-h">mars-stroke-h</option>
      <option data-icon="fa fa-neuter" value="fa-neuter">neuter</option>
      <option data-icon="fa fa-genderless" value="fa-genderless">genderless</option>
      <option data-icon="fa fa-facebook-official" value="fa-facebook-official">facebook-official</option>
      <option data-icon="fa fa-pinterest-p" value="fa-pinterest-p">pinterest-p</option>
      <option data-icon="fa fa-whatsapp" value="fa-whatsapp">whatsapp</option>
      <option data-icon="fa fa-server" value="fa-server">server</option>
      <option data-icon="fa fa-user-plus" value="fa-user-plus">user-plus</option>
      <option data-icon="fa fa-user-times" value="fa-user-times">user-times</option>
      <option data-icon="fa fa-bed" value="fa-bed">bed</option>
      <option data-icon="fa fa-viacoin" value="fa-viacoin">viacoin</option>
      <option data-icon="fa fa-train" value="fa-train">train</option>
      <option data-icon="fa fa-subway" value="fa-subway">subway</option>
      <option data-icon="fa fa-medium" value="fa-medium">medium</option>
      <option data-icon="fa fa-y-combinator" value="fa-y-combinator">y-combinator</option>
      <option data-icon="fa fa-optin-monster" value="fa-optin-monster">optin-monster</option>
      <option data-icon="fa fa-opencart" value="fa-opencart">opencart</option>
      <option data-icon="fa fa-expeditedssl" value="fa-expeditedssl">expeditedssl</option>
      <option data-icon="fa fa-battery-full" value="fa-battery-full">battery-full</option>
      <option data-icon="fa fa-battery-three-quarters" value="fa-battery-three-quarters">battery-three-quarters</option>
      <option data-icon="fa fa-battery-half" value="fa-battery-half">battery-half</option>
      <option data-icon="fa fa-battery-quarter" value="fa-battery-quarter">battery-quarter</option>
      <option data-icon="fa fa-battery-empty" value="fa-battery-empty">battery-empty</option>
      <option data-icon="fa fa-mouse-pointer" value="fa-mouse-pointer">mouse-pointer</option>
      <option data-icon="fa fa-i-cursor" value="fa-i-cursor">i-cursor</option>
      <option data-icon="fa fa-object-group" value="fa-object-group">object-group</option>
      <option data-icon="fa fa-object-ungroup" value="fa-object-ungroup">object-ungroup</option>
      <option data-icon="fa fa-sticky-note" value="fa-sticky-note">sticky-note</option>
      <option data-icon="fa fa-sticky-note-o" value="fa-sticky-note-o">sticky-note-o</option>
      <option data-icon="fa fa-cc-jcb" value="fa-cc-jcb">cc-jcb</option>
      <option data-icon="fa fa-cc-diners-club" value="fa-cc-diners-club">cc-diners-club</option>
      <option data-icon="fa fa-clone" value="fa-clone">clone</option>
      <option data-icon="fa fa-balance-scale" value="fa-balance-scale">balance-scale</option>
      <option data-icon="fa fa-hourglass-o" value="fa-hourglass-o">hourglass-o</option>
      <option data-icon="fa fa-hourglass-start" value="fa-hourglass-start">hourglass-start</option>
      <option data-icon="fa fa-hourglass-half" value="fa-hourglass-half">hourglass-half</option>
      <option data-icon="fa fa-hourglass-end" value="fa-hourglass-end">hourglass-end</option>
      <option data-icon="fa fa-hourglass" value="fa-hourglass">hourglass</option>
      <option data-icon="fa fa-hand-rock-o" value="fa-hand-rock-o">hand-rock-o</option>
      <option data-icon="fa fa-hand-paper-o" value="fa-hand-paper-o">hand-paper-o</option>
      <option data-icon="fa fa-hand-scissors-o" value="fa-hand-scissors-o">hand-scissors-o</option>
      <option data-icon="fa fa-hand-lizard-o" value="fa-hand-lizard-o">hand-lizard-o</option>
      <option data-icon="fa fa-hand-spock-o" value="fa-hand-spock-o">hand-spock-o</option>
      <option data-icon="fa fa-hand-pointer-o" value="fa-hand-pointer-o">hand-pointer-o</option>
      <option data-icon="fa fa-hand-peace-o" value="fa-hand-peace-o">hand-peace-o</option>
      <option data-icon="fa fa-trademark" value="fa-trademark">trademark</option>
      <option data-icon="fa fa-registered" value="fa-registered">registered</option>
      <option data-icon="fa fa-creative-commons" value="fa-creative-commons">creative-commons</option>
      <option data-icon="fa fa-gg" value="fa-gg">gg</option>
      <option data-icon="fa fa-gg-circle" value="fa-gg-circle">gg-circle</option>
      <option data-icon="fa fa-tripadvisor" value="fa-tripadvisor">tripadvisor</option>
      <option data-icon="fa fa-odnoklassniki" value="fa-odnoklassniki">odnoklassniki</option>
      <option data-icon="fa fa-odnoklassniki-square" value="fa-odnoklassniki-square">odnoklassniki-square</option>
      <option data-icon="fa fa-get-pocket" value="fa-get-pocket">get-pocket</option>
      <option data-icon="fa fa-wikipedia-w" value="fa-wikipedia-w">wikipedia-w</option>
      <option data-icon="fa fa-safari" value="fa-safari">safari</option>
      <option data-icon="fa fa-chrome" value="fa-chrome">chrome</option>
      <option data-icon="fa fa-firefox" value="fa-firefox">firefox</option>
      <option data-icon="fa fa-opera" value="fa-opera">opera</option>
      <option data-icon="fa fa-internet-explorer" value="fa-internet-explorer">internet-explorer</option>
      <option data-icon="fa fa-television" value="fa-television">television</option>
      <option data-icon="fa fa-contao" value="fa-contao">contao</option>
      <option data-icon="fa fa-500px" value="fa-500px">500px</option>
      <option data-icon="fa fa-amazon" value="fa-amazon">amazon</option>
      <option data-icon="fa fa-calendar-plus-o" value="fa-calendar-plus-o">calendar-plus-o</option>
      <option data-icon="fa fa-calendar-minus-o" value="fa-calendar-minus-o">calendar-minus-o</option>
      <option data-icon="fa fa-calendar-times-o" value="fa-calendar-times-o">calendar-times-o</option>
      <option data-icon="fa fa-calendar-check-o" value="fa-calendar-check-o">calendar-check-o</option>
      <option data-icon="fa fa-industry" value="fa-industry">industry</option>
      <option data-icon="fa fa-map-pin" value="fa-map-pin">map-pin</option>
      <option data-icon="fa fa-map-signs" value="fa-map-signs">map-signs</option>
      <option data-icon="fa fa-map-o" value="fa-map-o">map-o</option>
      <option data-icon="fa fa-map" value="fa-map">map</option>
      <option data-icon="fa fa-commenting" value="fa-commenting">commenting</option>
      <option data-icon="fa fa-commenting-o" value="fa-commenting-o">commenting-o</option>
      <option data-icon="fa fa-houzz" value="fa-houzz">houzz</option>
      <option data-icon="fa fa-vimeo" value="fa-vimeo">vimeo</option>
      <option data-icon="fa fa-black-tie" value="fa-black-tie">black-tie</option>
      <option data-icon="fa fa-fonticons" value="fa-fonticons">fonticons</option>
</select>