<div class="search">
		<input class="form-control form-control-sm block-search" placeholder="Search blocks" type="text" data-vvveb-action="blockSearch" data-vvveb-on="keyup">
		<button class="clear-backspace"  data-vvveb-action="clearBlockSearch">
			<i class="la la-close"></i>
		</button>
	</div>

<div class="drag-elements-sidepane sidepane">
	<div>
		
	<ul class="blocks-list clearfix" data-type="leftpanel">
	</ul>

	</div>
</div>